import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Authorized Page| Crafted Space",
    description: "Generated by create next app",
  };

interface Props {
    children: React.ReactNode
}

export default function layout({ children }: Props) {
    return (
    <div className="w-full h-full">{children}</div>
    )
}
