import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Sign Up | Crafted Space",
    description: "Generated by create next app",
  };

interface Props {
    children: React.ReactNode
}

export default function layout({ children }: Props) {
    return (
    <div>{children}</div>
    )
}
